### ISSUE TITLE
question: derive <title> tag from visualtitle

### ISSUE THREAD

**Issue by teschmitz** [miohtama/visualtitle#2]
Before I installed your add-on, I had somehow envisaged getting an extra "short title" field. I can see why you have done it the other way round as by adding a "long (visual) title", only h1 needs to be manipulated.

I am sometimes using very long page titles, which, of course, is a nuisance for breadcrumbs and portlet entries.

If I use the visualtitle for the long title and enter a short title in the original Title field, I see two effects:
1) the <title> tag will be derived from the short title
2) the short name (url) will be derived from the short title
#2 I can handle when editing the page although it might be a bit of a nuisance.

But is there a way to take the title tag from the visual name?

My main concern is impact on page ranking.

**Comment by miohtama** [comment]
Looks like `<title>` is generated by a viewlet so you could override it:

https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/common.py#L57

**Comment by teschmitz** [comment]
Thank you for the tip.
